### ISSUE TITLE
not building

### ISSUE THREAD

**Issue by pkoevesdi** [Mirror0/qspi-example#1]
It doesn't compile on my side at the moment, I'm trying to figure out why. 
First:
`error: '#[panic_handler]' function required, but not found`
After inserting `use panic_probe as _;` in `main.rs` I get several  `rust-lld: error: undefined symbol: _defmt*`.
But still I can see the intended usage in the source, hope, that helps.

**Comment by Mirror0** [comment]
Sorry, maybe I had some cached version or something. try use `use {defmt_rtt as _, panic_probe as _};` to resolve `panic_handler` error also I provided the same example to embassy project with some suggested changes, but I still have to fix some suggestions, It build on their CI so this maybe be of help to you.
Here:
https://github.com/Mirror0/embassy/blob/qspi-example/examples/stm32f7/src/bin/qspi.rs

**Comment by pkoevesdi** [comment]
Ahh, of course, that `defmt_rtt as _` is missing, I could have thought of that myself too. Now it builds. Thank You very much!

**Comment by pkoevesdi** [comment]
Maybe, You could take a look at:
https://github.com/embassy-rs/embassy/issues/2926
It's not directly Your qspi module, but the very similar ospi.
